name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: CI=false yarn build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email

        git clone git@github.com:songiapp/songiapp.github.io.git
        cd songiapp.github.io
        rm -rf static
        cp -r ../build/* .
        git add .
        git commit -m "web build"
        git push
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
